// Code generated by goctl. DO NOT EDIT.
package types

type BindKeplrReq struct {
	Address string `json:"address"`
	Sign    string `json:"sign"`
}

type ClosedInfo struct {
	ToTal  float64 `json:"total"`  // 全部收益
	Reward float64 `json:"reward"` // 节点收益
	TTNT   float64 `json:"ttnt"`
	Ratio  float64 `json:"ratio"` // 多少reward可以换1个ttnt
}

type CommonInfo struct {
	ToTal          float64 `json:"total"`          // 全部收益
	Reward         float64 `json:"reward"`         // 节点收益/任务收益
	ReferralReward float64 `json:"referralReward"` // 邀请好友收益
	TTNT           float64 `json:"ttnt"`
	Ratio          float64 `json:"ratio"` // 多少reward可以换1个ttnt
}

type GetVerifyCodeReq struct {
	Username string `form:"username"`
}

type HerschelInfo struct {
	ToTal             float64 `json:"total"`             // 全部收益
	Reward            float64 `json:"reward"`            // 节点收益
	ReferralReward    float64 `json:"referralReward"`    // 邀请好友收益
	KOLReferralReward float64 `json:"kolReferralReward"` // KOL邀请好友收益
	TTNT              float64 `json:"ttnt"`
	Ratio             float64 `json:"ratio"` // 多少reward可以换1个ttnt
}

type LoginReq struct {
	Username   string `json:"username"`            // 邮箱或钱包地址
	Sign       string `json:"sign,optional"`       // 钱包签名
	VerifyCode string `json:"verifyCode,optional"` // 邮箱验证码
}

type LoginResp struct {
	Token string `json:"token"`
}

type RewardDetail struct {
	Closed   ClosedInfo   `json:"closed"`   // 封测奖励
	Huygens  CommonInfo   `json:"huygens"`  // 惠更斯测试网
	Herschel HerschelInfo `json:"herschel"` // 郝歇尔测试网
	AirDrop  CommonInfo   `json:"airdrop"`  // 社区活动
}

type RewardInfo struct {
	Email  TTNTInfo  `json:"email"`  // 邮箱的奖励信息
	Wallet TTNTInfo  `json:"wallet"` // 钱包地址的奖励信息
	User   UserInfo  `json:"user"`   // 我的信息
	Reward RewardSum `json:"reward"` // 累计奖励
	Status int64     `json:"status"` // 提现状态 0-未提现 1-提现中 2-已提现
}

type RewardMap struct {
	Reward float64 `json:"reward"`
	TTNT   float64 `json:"ttnt"`
}

type RewardSum struct {
	Total float64   `json:"total"`
	TNT1  RewardMap `json:"tnt1"`
	TNT2  RewardMap `json:"tnt2"`
	TCP   RewardMap `json:"tcp"`
}

type TTNTInfo struct {
	Address string  `json:"address"`
	Value   float64 `json:"value"`
}

type UserInfo struct {
	Email string `json:"email"`
	ETH   string `json:"eth"`
	Titan string `json:"titan"`
}

type VerifyCodeResp struct {
	VerifyCode string `json:"verifyCode"`
}
