// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userMissionFieldNames          = builder.RawFieldNames(&UserMission{})
	userMissionRows                = strings.Join(userMissionFieldNames, ",")
	userMissionRowsExpectAutoSet   = strings.Join(stringx.Remove(userMissionFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	userMissionRowsWithPlaceHolder = strings.Join(stringx.Remove(userMissionFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	userMissionModel interface {
		Insert(ctx context.Context, data *UserMission) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*UserMission, error)
		Update(ctx context.Context, data *UserMission) error
		Delete(ctx context.Context, id int64) error
	}

	defaultUserMissionModel struct {
		conn  sqlx.SqlConn
		table string
	}

	UserMission struct {
		Id       int64  `db:"id"`
		Username string `db:"username"` // 用户名称,邮箱/钱包地址
		Credit   int64  `db:"credit"`   // 社区任务收益
	}
)

func newUserMissionModel(conn sqlx.SqlConn) *defaultUserMissionModel {
	return &defaultUserMissionModel{
		conn:  conn,
		table: "`user_mission`",
	}
}

func (m *defaultUserMissionModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultUserMissionModel) FindOne(ctx context.Context, id int64) (*UserMission, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userMissionRows, m.table)
	var resp UserMission
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserMissionModel) Insert(ctx context.Context, data *UserMission) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?)", m.table, userMissionRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Username, data.Credit)
	return ret, err
}

func (m *defaultUserMissionModel) Update(ctx context.Context, data *UserMission) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, userMissionRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Username, data.Credit, data.Id)
	return err
}

func (m *defaultUserMissionModel) tableName() string {
	return m.table
}
